/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;
import Controlador.ContorladorCaja;
import Controlador.ContorladorCochera;
import Controlador.ControladorCliente;
import Controlador.Controladornuevovehiculo;
import Modelo.TipoVehiculo;
import java.time.LocalTime;
import javax.swing.JOptionPane;


/**
 *
 * @author Rafa
 */
public class ITZingresocliente extends javax.swing.JFrame {
    ContorladorCaja ctr = new ContorladorCaja();
    ControladorCliente ctrc = new ControladorCliente();
    Controladornuevovehiculo ctrnv = new Controladornuevovehiculo();
    ContorladorCochera ctrch = new ContorladorCochera();
    public ITZingresocliente() {
        initComponents();
        BTNcerrarcaja.setVisible(false);
        BTNcajabuscar.setVisible(true);
        actualizarCBtipovehiculo();
        actualizarCBcochera();
        mostrar(ctrc.mostrartodo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSeparator1 = new javax.swing.JSeparator();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TBdni = new javax.swing.JTextField();
        TBpatente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CBtipovehiculo = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        CBcochera = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        TBhoraentrada = new javax.swing.JTextField();
        TBhoraactual = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        BTNagregar = new javax.swing.JButton();
        BTNvehiculobuscar = new javax.swing.JButton();
        BTNvehiculoeditar = new javax.swing.JButton();
        BTNeliminar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        TBfecha = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TBcajainicial = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        TBicajaingreso = new javax.swing.JTextField();
        TBcajagasto = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        LBLcajafinal = new javax.swing.JLabel();
        BTNsalidavehiculo = new javax.swing.JButton();
        BTNcochera = new javax.swing.JButton();
        BTNtvehiculo = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        TBcajabuscar = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        BTNañadir = new javax.swing.JButton();
        BTNcrearcaja = new javax.swing.JButton();
        BTNcerrarcaja = new javax.swing.JButton();
        BTNeditarcaja = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        LBLfecha = new javax.swing.JLabel();
        BTNcajabuscar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setText("caja");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel2.setText("ingreso de vehiculo");

        jLabel3.setText("DNI");

        jLabel4.setText("Patente");

        jLabel5.setText("Tipo de vehiculo");

        jLabel6.setText("Cochera");

        jLabel7.setText("Hora de entrada");

        TBhoraactual.setText("hora actual");
        TBhoraactual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBhoraactualActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "PATENTE", "FECHA", "DNI", "HORA DE ENTRADA", "HORA DE SALIDA", "COCHERA", "TIPO DE VEHICULO"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        BTNagregar.setText("Agregar");
        BTNagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarActionPerformed(evt);
            }
        });

        BTNvehiculobuscar.setText("Buscar");

        BTNvehiculoeditar.setText("Editar");

        BTNeliminar.setText("Eliminar");

        jLabel8.setText("Fecha");

        jLabel9.setText("Caja inicial");

        jLabel10.setText("Ingreso");

        jLabel11.setText("Gasto");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel12.setText("Caja final actual");

        LBLcajafinal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        LBLcajafinal.setText("0");

        BTNsalidavehiculo.setText("Retirar vehiculo");
        BTNsalidavehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNsalidavehiculoActionPerformed(evt);
            }
        });

        BTNcochera.setText("Agregar una nueva cochera");
        BTNcochera.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcocheraActionPerformed(evt);
            }
        });

        BTNtvehiculo.setText("Agregar un nuevo tipo de vehiculo");
        BTNtvehiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNtvehiculoActionPerformed(evt);
            }
        });

        TBcajabuscar.setText("Mostrar todo");
        TBcajabuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TBcajabuscarActionPerformed(evt);
            }
        });

        jLabel13.setText("YYYY-MM-DD");

        BTNañadir.setText("Añadir");
        BTNañadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNañadirActionPerformed(evt);
            }
        });

        BTNcrearcaja.setText("Crear");
        BTNcrearcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcrearcajaActionPerformed(evt);
            }
        });

        BTNcerrarcaja.setText("Cerrar");
        BTNcerrarcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcerrarcajaActionPerformed(evt);
            }
        });

        BTNeditarcaja.setText("Editar");
        BTNeditarcaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeditarcajaActionPerformed(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel14.setText("Fecha:");

        LBLfecha.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LBLfecha.setText("----------");

        BTNcajabuscar.setText("Buscar");
        BTNcajabuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNcajabuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator2)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BTNtvehiculo, javax.swing.GroupLayout.DEFAULT_SIZE, 212, Short.MAX_VALUE)
                            .addComponent(BTNcochera, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(5, 5, 5)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(LBLfecha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel10)
                                            .addComponent(jLabel11))
                                        .addGap(68, 68, 68))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(BTNcajabuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGap(8, 8, 8)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TBcajagasto)
                                    .addComponent(TBicajaingreso)
                                    .addComponent(BTNcerrarcaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(BTNañadir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel13))
                                    .addComponent(jLabel9))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TBfecha)
                                    .addComponent(TBcajainicial)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(LBLcajafinal))
                                    .addComponent(TBcajabuscar))
                                .addGap(4, 4, 4))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNcrearcaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNeditarcaja, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5)
                            .addComponent(jLabel3))
                        .addGap(40, 40, 40)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CBtipovehiculo, 0, 111, Short.MAX_VALUE)
                            .addComponent(TBdni)
                            .addComponent(CBcochera, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel7)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(24, 24, 24)
                                        .addComponent(jLabel4)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TBpatente, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(TBhoraentrada, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(BTNagregar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(BTNvehiculobuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(TBhoraactual, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(100, 100, 100))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(47, 47, 47)
                                .addComponent(BTNsalidavehiculo)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BTNvehiculoeditar, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BTNeliminar))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(4, 4, 4)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 679, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(245, 245, 245)
                                        .addComponent(jLabel2)))
                                .addGap(0, 25, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(LBLfecha))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(TBfecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel13)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TBcajainicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTNcrearcaja)
                                    .addComponent(BTNeditarcaja))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BTNcerrarcaja)
                            .addComponent(BTNcajabuscar))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBicajaingreso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TBcajagasto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNañadir)
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(LBLcajafinal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TBcajabuscar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BTNcochera, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(BTNtvehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jLabel4)
                                            .addComponent(TBpatente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(TBhoraentrada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel7))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(TBhoraactual, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(27, 27, 27)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(BTNagregar)
                                            .addComponent(BTNvehiculobuscar)))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(34, 34, 34)
                                        .addComponent(jLabel5)
                                        .addGap(42, 42, 42)
                                        .addComponent(jLabel6)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 324, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(BTNeliminar)
                                    .addComponent(BTNvehiculoeditar)
                                    .addComponent(BTNsalidavehiculo)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(TBdni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(CBtipovehiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(CBcochera, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(jSeparator1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BTNañadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNañadirActionPerformed
        ctr.ingresogasto(TBfecha.getText(), TBicajaingreso.getText(), TBcajagasto.getText());
        System.out.print(TBfecha.getText());
        actualizarlbl(TBfecha.getText());
        TBicajaingreso.setText("");
        TBcajagasto.setText("");
    }//GEN-LAST:event_BTNañadirActionPerformed

    private void BTNcrearcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcrearcajaActionPerformed
        if(ctr.crear(TBfecha.getText(), TBcajainicial.getText())){ //ejecuta el metodo crear del parametro y si se ejecuta correctamente se ejecutara elr esto del codigo
            actualizarlbl(TBfecha.getText());
            LBLfecha.setText(TBfecha.getText());
            TBfecha.setVisible(false);
            TBcajainicial.setVisible(false);
            
            BTNcerrarcaja.setVisible(true);
            BTNcajabuscar.setVisible(false);
            BTNcrearcaja.setVisible(false);
            BTNeditarcaja.setVisible(false);
        }else{
            JOptionPane.showMessageDialog(null,"Error\nDatos invalidos.");  
        }
    }//GEN-LAST:event_BTNcrearcajaActionPerformed

    private void BTNcerrarcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcerrarcajaActionPerformed
        LBLfecha.setText("----------");
        TBfecha.setVisible(true);
        TBcajainicial.setVisible(true); 
        TBfecha.setText("");
        TBcajainicial.setText("");
        LBLcajafinal.setText("0");
        
        BTNcerrarcaja.setVisible(false);
        BTNcajabuscar.setVisible(true);
        BTNcrearcaja.setVisible(true);
        BTNeditarcaja.setVisible(true);
    }//GEN-LAST:event_BTNcerrarcajaActionPerformed

    private void BTNeditarcajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeditarcajaActionPerformed
        if(ctr.editar(TBfecha.getText(), TBcajainicial.getText())){
            actualizarlbl(TBfecha.getText());
            LBLfecha.setText(TBfecha.getText());
            TBfecha.setVisible(false);
            TBcajainicial.setVisible(false); 
            
            BTNcerrarcaja.setVisible(true);
            BTNcajabuscar.setVisible(false);
            BTNcrearcaja.setVisible(false);
            BTNeditarcaja.setVisible(false);
        }
    }//GEN-LAST:event_BTNeditarcajaActionPerformed

    private void TBcajabuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBcajabuscarActionPerformed
        cajabuscar abrir = new cajabuscar();
        abrir.setVisible(true);
    }//GEN-LAST:event_TBcajabuscarActionPerformed

    private void BTNcocheraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcocheraActionPerformed
        ITZcochera abrir = new ITZcochera();
        abrir.setVisible(true);
    }//GEN-LAST:event_BTNcocheraActionPerformed

    private void BTNtvehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNtvehiculoActionPerformed
        ITZnuevotipodevehiculo abrir = new ITZnuevotipodevehiculo();
        abrir.setVisible(true);
    }//GEN-LAST:event_BTNtvehiculoActionPerformed
/***
 * 
 * @param evt 
 */
    private void BTNagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarActionPerformed
            ctrc.crear(CBtipovehiculo.getSelectedIndex(), TBpatente.getText(), CBcochera.getSelectedIndex(), TBdni.getText(), TBhoraentrada.getText(), LBLfecha.getText());
            mostrar(ctrc.mostrartodo());
    }//GEN-LAST:event_BTNagregarActionPerformed

    private void TBhoraactualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TBhoraactualActionPerformed
        TBhoraentrada.setText(Integer.toString(LocalTime.now().getHour())+":"+Integer.toString(LocalTime.now().getMinute()));
    }//GEN-LAST:event_TBhoraactualActionPerformed

    
    /**
 * String entr = obtiene la hora de entrada de la tabla, 
 * String pat = obtiene la patente de la tabla
 * ejecuta el metodo retirarvehiculo de la controladora
 * 
 * Cuando se retira un vehiculo se libera espacio en la cochera donde estaba estacionado
 * int f = es igual a la esta entre la cantidad de espacios ocupados que tiene la cochera y la cantidad de lugares que ocupaba el vehiculo que se retiro,
 * para saber cuantos espacios ocupados tiene la cochera se busca en que cochera estaba estacionado el vehiculo a travez del nombre de la cochera y despues se hace un proceso similar para
 * saber cuantos lugares ocupa ese tipo de vehiculo
 * 
 * despues se ejecuta el metodo editar ocupaciones de la controladora de la cochera
 * @param evt 
 */
    private void BTNsalidavehiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNsalidavehiculoActionPerformed
        if((jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4)).equals("00:00:00")){
            //retirar vehiculo
            String entr = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3).toString();
            String pat = jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0).toString();
            ctrc.retirarvehiculo(entr, pat);
            
            //actualizar las ocupaciones disponibles en la base de datos
            int a = ctrch.mostrar(ctrch.indice(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5).toString())).getOcdisponibles();  
            int b = ctrnv.mostrar(ctrnv.indice(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6).toString())).getCantPlazasQueOcupa();
            int f = a-b;

            ctrch.editarocupacion(f, ctrch.indice(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5).toString()));
            
            //calcular total de horas estacionado

            LocalTime he = LocalTime.parse(jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3).toString());  //hora de entrada 
            int id =ctrnv.indice( jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 6).toString());   //id del tipo de vehiculo
            float total = ctrc.APagar(he, id);
            
            JOptionPane.showMessageDialog(null,"Coste del vehiculo retirado: $"+ total);
            
            //agregar el coste calculado a la caja del dia
            ctr.ingresogasto(LBLfecha.getText(), Float.toString(total), "0");
            
            //actualizar el lbl de la caja final
            actualizarlbl(LBLfecha.getText());
            
        } else {JOptionPane.showMessageDialog(null,"Error\nEl vehiculo ya fue retirado.");}
        mostrar(ctrc.mostrartodo());
    }//GEN-LAST:event_BTNsalidavehiculoActionPerformed

    private void BTNcajabuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNcajabuscarActionPerformed
        JOptionPane.showMessageDialog(null,ctr.mostrar(TBfecha.getText()).toString());
    }//GEN-LAST:event_BTNcajabuscarActionPerformed
    
    public void actualizarlbl(String fecha){
        float value = ctr.obtenercajafinal(fecha);
        LBLcajafinal.setText(Float.toString(value));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITZingresocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITZingresocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITZingresocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITZingresocliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITZingresocliente().setVisible(true);
            }
        });
    }
    
    public void actualizarCBtipovehiculo(){
        int contador=0;
        for (TipoVehiculo mostrartodo : ctrnv.mostrartodo()) {
            CBtipovehiculo.addItem(ctrnv.mostrartodo().get(contador).toString());
            contador++;
        }
    }
    
     public void actualizarCBcochera(){
        int cont=0;
        for(cont=0; cont < ctrch.mostrartodo().size();cont++){
            CBcochera.addItem(ctrch.mostrartodo().get(cont).toString());
        }
    }
     
         public void mostrar(String[][] lista){
        int i;
        String matriz[][] = new String[lista.length][7];
        for (i = 0; i<lista.length; i++){
            matriz[i][0]=lista[i][0];
            matriz[i][1]=lista[i][1];
            matriz[i][2]=lista[i][2];
            matriz[i][3]=lista[i][3];
            matriz[i][4]=lista[i][4];
            matriz[i][5]=lista[i][5];
            matriz[i][6]=lista[i][6];
        }
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "PATENTE","FECHA", "DNI", "HORA DE ENTRADA","HORA DE SALIDA","COCHERA","TIPO DE VEHICULO"
            }
        ));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNagregar;
    private javax.swing.JButton BTNañadir;
    private javax.swing.JButton BTNcajabuscar;
    private javax.swing.JButton BTNcerrarcaja;
    private javax.swing.JButton BTNcochera;
    private javax.swing.JButton BTNcrearcaja;
    private javax.swing.JButton BTNeditarcaja;
    private javax.swing.JButton BTNeliminar;
    private javax.swing.JButton BTNsalidavehiculo;
    private javax.swing.JButton BTNtvehiculo;
    private javax.swing.JButton BTNvehiculobuscar;
    private javax.swing.JButton BTNvehiculoeditar;
    private javax.swing.JComboBox<String> CBcochera;
    private javax.swing.JComboBox<String> CBtipovehiculo;
    private javax.swing.JLabel LBLcajafinal;
    private javax.swing.JLabel LBLfecha;
    private javax.swing.JButton TBcajabuscar;
    private javax.swing.JTextField TBcajagasto;
    private javax.swing.JTextField TBcajainicial;
    private javax.swing.JTextField TBdni;
    private javax.swing.JTextField TBfecha;
    private javax.swing.JButton TBhoraactual;
    private javax.swing.JTextField TBhoraentrada;
    private javax.swing.JTextField TBicajaingreso;
    private javax.swing.JTextField TBpatente;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
