/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.Controladornuevovehiculo;
import Modelo.TipoVehiculo;
import Modelo.dao.DAOtipovehiculo;
import java.util.List;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafa
 */
public class ITZnuevotipodevehiculo extends javax.swing.JFrame {
    Controladornuevovehiculo ctr = new Controladornuevovehiculo();
    public ITZnuevotipodevehiculo() {
        
        initComponents();
        mostrar(ctr.mostrartodo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        BTNagregar = new javax.swing.JButton();
        BTNelimiar = new javax.swing.JButton();
        BTNeditar = new javax.swing.JButton();
        TBnombre = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        TBpreciohora = new javax.swing.JTextField();
        TBplazasocupadas = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Jtabletvehiculos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setText("Nuevo tipo de vehiculo");

        BTNagregar.setText("Agregar");
        BTNagregar.setNextFocusableComponent(BTNeditar);
        BTNagregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNagregarActionPerformed(evt);
            }
        });

        BTNelimiar.setText("Eliminar");
        BTNelimiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNelimiarActionPerformed(evt);
            }
        });

        BTNeditar.setText("Editar");
        BTNeditar.setNextFocusableComponent(BTNelimiar);
        BTNeditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNeditarActionPerformed(evt);
            }
        });

        TBnombre.setNextFocusableComponent(TBplazasocupadas);

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        TBpreciohora.setNextFocusableComponent(BTNagregar);

        TBplazasocupadas.setNextFocusableComponent(TBpreciohora);

        jLabel2.setText("Nombre");

        jLabel3.setText("Precio por hora");

        jLabel4.setText("Plazas ocupadas");

        Jtabletvehiculos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "PLAZAS OCUPADAS", "PRECIO POR HORA"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        Jtabletvehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        Jtabletvehiculos.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(Jtabletvehiculos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(TBpreciohora, javax.swing.GroupLayout.DEFAULT_SIZE, 90, Short.MAX_VALUE)
                            .addComponent(TBnombre)
                            .addComponent(TBplazasocupadas)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BTNagregar, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                        .addGap(43, 43, 43)
                        .addComponent(BTNeditar, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 2, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(BTNelimiar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(12, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BTNelimiar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jSeparator1)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TBnombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel2))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TBplazasocupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel4))
                            .addGap(30, 30, 30)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(TBpreciohora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel3))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(BTNagregar)
                                .addComponent(BTNeditar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Crea el obeto DAOtipovehiculo con los datos de los text boxes del formulario
     * ejecuta el metodo "crear"
     * muestra un mensaje de que se agrego
     * despues actualiza la tabla donde se ven los datos
     * elimina los textos de los text boxes para que queden en blanco
     */
    private void BTNagregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNagregarActionPerformed
        ctr.crear(TBnombre.getText(),TBpreciohora.getText(), TBplazasocupadas.getText());
        mostrar(ctr.mostrartodo());
        TBnombre.setText("");
        TBpreciohora.setText("");
        TBplazasocupadas.setText("");
    }//GEN-LAST:event_BTNagregarActionPerformed
    /**
    * guarda el valor de la fila seleccionada y la columna 0 (donde esta el id) en un object ya que es lo que devulve el metodo selectedrow
    * llama a la controladora para eliminar
    * llama a la controladora para actualizar la tabla
     */
    private void BTNelimiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNelimiarActionPerformed
        Object key = Jtabletvehiculos.getValueAt(Jtabletvehiculos.getSelectedRow(), 0);
        ctr.eliminar(key);
        mostrar(ctr.mostrartodo());
    }
        /*
        No puedo borrar esta linea
        mostrar(l.readALL());    }//GEN-LAST:event_BTNelimiarActionPerformed
        */
    
    /**
     * @param evt 
     */
    private void BTNeditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNeditarActionPerformed
        ctr.editar((String) Jtabletvehiculos.getValueAt(Jtabletvehiculos.getSelectedRow(), 0), TBnombre.getText(), TBpreciohora.getText(),TBplazasocupadas.getText());  
        mostrar(ctr.mostrartodo());
        TBnombre.setText("");
        TBpreciohora.setText("");  
        TBplazasocupadas.setText(""); 
    }//GEN-LAST:event_BTNeditarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ITZnuevotipodevehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ITZnuevotipodevehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ITZnuevotipodevehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ITZnuevotipodevehiculo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ITZnuevotipodevehiculo().setVisible(true);
            }
        });
    }
        /**
     * @param array list de TipoVehiculo
     * @method mostrar list(TipoVehiculo), este metodo recive una lista llamando al metodo readall de la clase DAOCocheras
     * Crea una matriz con los datos de esta lista
     * Asigna esta nueva matriz a la matriz de la tabla
     */
public void mostrar(List<TipoVehiculo> lista){
        int i;
        String matriz[][] = new String[lista.size()][4];
        for (i = 0; i<lista.size(); i++){
            matriz[i][0]=Integer.toString(lista.get(i).getId());
            matriz[i][1]=lista.get(i).getNombre();
            matriz[i][2]=Float.toString(lista.get(i).getPrecioPorHora());
            matriz[i][3]="$ "+Integer.toString(lista.get(i).getCantPlazasQueOcupa());
        }
        Jtabletvehiculos.setModel(new javax.swing.table.DefaultTableModel(
            matriz,
            new String [] {
                "ID", "NOMBRE","PLAZAS OCUPADAS","PRECIO POR HORA"
            }
        ));
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNagregar;
    private javax.swing.JButton BTNeditar;
    private javax.swing.JButton BTNelimiar;
    private javax.swing.JTable Jtabletvehiculos;
    private javax.swing.JTextField TBnombre;
    private javax.swing.JTextField TBplazasocupadas;
    private javax.swing.JTextField TBpreciohora;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
